sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.204.101
    port: 3306
    database: sky_take_out
    username: root
    password: mysqlmima
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: sky114
  redis:
    host: 192.168.204.101
    port: 6379
